# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: torchmind/circleci-openjdk:8-jdk-browsers
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: git lfs pull
      - restore_cache:
          keys:
          - build-cache
      - run: gradle dependencies
      - run: gradle setupCiWorkspace
      - save_cache:
          paths:
            - ~/.gradle
          key: build-cache
      - run: gradle build createExe
      - run: |
          mkdir /tmp/artifacts/
          cp liteloader/build/libs/MineClock.litemod /tmp/artifacts/
          cp ui/build/libs/MineClock.jar /tmp/artifacts/
          cp ui/build/launch4j/MineClock.exe /tmp/artifacts/
      - store_artifacts:
          path: /tmp/artifacts/
          destination: /
